services:
  backend:
    container_name: hubxp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env.development
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: