services:
  backend:
    container_name: hubxp
    stdin_open: true 
    tty: true        
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - mongodb
    volumes:
      - ./app:/code/app
    entrypoint: 
      - "/bin/sh"
      - "-ecx"
      - >
        python ./populate_mongo.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir "/code/app"
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env.development
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: